server:
  port: 6060

spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: Qwerty@123
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://localhost:6062
