
server:
  port: 6061

spring:
  application:
    name: OrderService

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Qwerty@123
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://localhost:6062

resilience4j:
  circuitbreaker:
         instances:
             external:
               event-consumer-buffer-size: 10
               failure-rate-threshold: 50
               minimum-number-of-calls: 5
               automatic-transition-from-open-to-half-open-enabled: true
               wait-duration-in-open-state: 5s
               permitted-number-of-calls-in-half-open-state: 3
               sliding-window-size: 10
               Sliding-window-type: COUNT_BASE